/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_numbaseball_MainActivity */

#ifndef _Included_com_example_numbaseball_MainActivity
#define _Included_com_example_numbaseball_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_numbaseball_MainActivity
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_numbaseball_MainActivity_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_example_numbaseball_MainActivity
 * Method:    startNumbaseball
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_numbaseball_MainActivity_startNumbaseball
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_numbaseball_MainActivity
 * Method:    closeDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_numbaseball_MainActivity_closeDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
